default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: brazilian_cities_app_development

test:
  <<: *default
  database: brazilian_cities_app_test

production:
  <<: *default
  database: brazilian_cities_app_production
  username: <%= ENV['DB_PRODUCTION_USERNAME'] %>
  password: <%= ENV['DB_PRODUCTION_PASSWORD'] %>
